version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "4000:3002"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  database:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  postgres_data: